#Config file for Kalman Parameters

#Lugre Kalman Filter
lugre_ekf:

  #Matrix P -> this is currently being overwritten by the zero initial state 
  initial_estimate_covariance: [1e-6, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     # zx_fl
                                0,    1e-6, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     # zy_fl
                                0,    0,    1e-1, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     # w_fl
                                0,    0,    0,    1e-6, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     # zx_fr
                                0,    0,    0,    0,    1e-6, 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     # zy_fr
                                0,    0,    0,    0,    0,    1e-1, 0,    0,    0,    0,    0,    0,    0,    0,    0,     # w_fr
                                0,    0,    0,    0,    0,    0,    1e-6, 0,    0,    0,    0,    0,    0,    0,    0,     # zx_rl
                                0,    0,    0,    0,    0,    0,    0,    1e-6, 0,    0,    0,    0,    0,    0,    0,     # zy_rl
                                0,    0,    0,    0,    0,    0,    0,    0,    1e-1, 0,    0,    0,    0,    0,    0,     # w_rl
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-6, 0,    0,    0,    0,    0,     # zx_rr
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-6, 0,    0,    0,    0,     # zy_rr
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-1, 0,    0,    0,     # w_rr
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-1, 0,    0,     # vx
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-1, 0,     # vy
                                0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-1]  # wz 
  
  #Matrix Q
  process_covariance:  [1e-6, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                        0,    1e-6, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                        0,    0,    1e-1, 0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                        0,    0,    0,    1e-6, 0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                        0,    0,    0,    0,    1e-6, 0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                        0,    0,    0,    0,    0,    1e-1, 0,     0,     0,    0,    0,    0,    0,    0,    0,
                        0,    0,    0,    0,    0,    0,    1e-6,  0,     0,    0,    0,    0,    0,    0,    0,
                        0,    0,    0,    0,    0,    0,    0,     1e-6,  0,    0,    0,    0,    0,    0,    0,
                        0,    0,    0,    0,    0,    0,    0,     0,     1e-1, 0,    0,    0,    0,    0,    0,
                        0,    0,    0,    0,    0,    0,    0,     0,     0,    1e-6, 0,    0,    0,    0,    0,
                        0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    1e-6, 0,    0,    0,    0,
                        0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    1e-1, 0,    0,    0,
                        0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    5e-4, 0,    0,
                        0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    5e-4, 0,
                        0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    1e-2]

  #Matrix R
  measurement_covariance:  [1e-4,    0,       0,       0,       0,     0,    0,     0,     0,      #w_FL
                            0,       1e-4,    0,       0,       0,     0,    0,     0,     0,      #w_FR
                            0,       0,       1e-4,    0,       0,     0,    0,     0,     0,      #w_RL
                            0,       0,       0,       1e-4,    0,     0,    0,     0,     0,      #w_RR
                            0,       0,       0,       0,       0.3,   0,    0,     0,     0,      #a_x
                            0,       0,       0,       0,       0,     0.1,  0,     0,     0,      #a_y
                            0,       0,       0,       0,       0,     0,    1e6,   0,     0,      #GPS v_x
                            0,       0,       0,       0,       0,     0,    0,     1e6,   0,      #GPS v_y
                            0,       0,       0,       0,       0,     0,    0,     0,     1e-4]  #yaw_rate



#GPS Position Kalman Filter
gps_ekf:

  #If you want to use the gps for correction in the position estimation
  use_gps: false

  #Matrix P
  initial_estimate_covariance: [1e-5, 0,    0,
                                0,    1e-5, 0,
                                0,    0,    1e-5]

  #Matrix Q
  process_covariance:  [1e-2, 0,    0,
                        0,    1e-2, 0,
                        0,    0,    1e-4]
  
  #Matrix R
  measurement_covariance:  [1e-2, 0,    0,
                            0,    1e-2, 0,
                            0,    0,    1e-2]
