#Config file for Kalman Parameters

#Lugre Kalman Filter
lugre_ekf:

  #Matrix P
  initial_estimate_covariance: [1e-1, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    1e-1, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    1e-1, 0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    1e-1, 0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    1e-1, 0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    1e-1, 0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    1e-1,  0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     1e-1,  0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     1e-1, 0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    1e-1, 0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    1e-1, 0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    1e-1, 0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    1e-1, 0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    1e-1, 0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    1e-1]
  
  #Matrix Q
  process_covariance:  [1e-4, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                        0,    1e-4, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                        0,    0,    1e1, 0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                        0,    0,    0,    1e-4, 0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                        0,    0,    0,    0,    1e-4, 0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                        0,    0,    0,    0,    0,    1e1, 0,     0,     0,    0,    0,    0,    0,    0,    0,
                        0,    0,    0,    0,    0,    0,    1e-4,  0,     0,    0,    0,    0,    0,    0,    0,
                        0,    0,    0,    0,    0,    0,    0,     1e-4,  0,    0,    0,    0,    0,    0,    0,
                        0,    0,    0,    0,    0,    0,    0,     0,     1e1, 0,    0,    0,    0,    0,    0,
                        0,    0,    0,    0,    0,    0,    0,     0,     0,    1e-4, 0,    0,    0,    0,    0,
                        0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    1e-4, 0,    0,    0,    0,
                        0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    1e1, 0,    0,    0,
                        0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    1e-3, 0,    0,
                        0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    1e-3, 0,
                        0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    1e-3]

  #Matrix R
  measurement_covariance:  [1e-4, 0,       0,       0,       0,     0,    0,     0,     0,      #v_FL
                            0,       1e-4, 0,       0,       0,     0,    0,     0,     0,      #v_FR
                            0,       0,       1e-4, 0,       0,     0,    0,     0,     0,      #v_RL
                            0,       0,       0,       1e-4, 0,     0,    0,     0,     0,      #v_RR
                            0,       0,       0,       0,       0.3,   0,    0,     0,     0,      #a_x
                            0,       0,       0,       0,       0,     0.3,  0,     0,     0,      #a_y
                            0,       0,       0,       0,       0,     0,    10000, 0,     0,      #GPS v_x
                            0,       0,       0,       0,       0,     0,    0,     10000, 0,      #GPS v_y
                            0,       0,       0,       0,       0,     0,    0,     0,     1e-4]  #yaw_rate


#GPS Position Kalman Filter
gps_ekf:

  #If you want to use the gps for correction in the position estimation
  use_gps: false

  #Matrix P
  initial_estimate_covariance: [1e-5, 0,    0,
                                0,    1e-5, 0,
                                0,    0,    1e-5]

  #Matrix Q
  process_covariance:  [1e-2, 0,    0,
                        0,    1e-2, 0,
                        0,    0,    1e-4]
  
  #Matrix R
  measurement_covariance:  [1e-2, 0,    0,
                            0,    1e-2, 0,
                            0,    0,    1e-2]
