car:

  inertia:
    m: 206.3       # car mass without driver
    g: 9.81        # since when is there gravity
    Iz: 150        # same shit different day
    unsprung: 52.0 # wheel mass

  kinematics:
    track: 1.2
    a: 0.780 #0.52 * wheelbase (1.54m) not validated yet
    b: 0.760 #0.48 * wheelbase (1.54m) not validated yet
    h: 0.29 #cg height

  aero:
    rho:  1.225
    cl:   4.0   # caralhada
    dist: 0.465  # ratio
    cd :  1.62 

  engine:
    gr: 12.65 #true

  tire:
    # Bristle Stiffness -> It determines the initial slope of the tire's force-slip curve
    sigma_00: 300
    sigma_01: 300

    # Bristle Damping -> This represents the internal damping (energy dissipation) of the rubber itself as the bristles bend and snap back
    sigma_10: 0.8
    sigma_11: 0.8

    # Viscous Friction -> This is the standard viscous drag coefficient
    sigma_20: 0.01
    sigma_21: 0.01

    J_f: 1.0 # cad feito pelo diogo
    J_r: 1.0

    mu_k_00: 0.5
    mu_k_01: 0.0
    mu_k_10: 0.0
    mu_k_11: 0.5

    mu_s_00: 2.5
    mu_s_01: 0.0
    mu_s_10: 0.0
    mu_s_11: 2.5

    gamma: 1.0 # slope
    vs: 12.0 # velocity which you are slipping
    
    kx: 1.4 #not used
    ky: 1.4 #not used
    
    kz: 96000 #vertical stiffness from ttc
     
    r: 0.205 # vd

  gps: #fuck gps none of my homies have gps
    use_gps_velocities: true # this is not for the position Kalman, this is for the code to derive the velocities according to position of the GPS
    coord_x: 0
    coord_y: 0

  median_filters: 
    use_median_filters: false
    imu_window_size: 3
    wheel_speeds_window_size: 3
    torque_window_size: 3
