#FST10D car parameters


#    fl      track   fr
#  (a,w_2)0--------0(a,-w_2)
#              | a
#              | 
#              | CG (0,0)
#              | 
#        rl    | b    rr
# (-b,w_2)0--------0(-b,-w_2)


car:

  inertia:
    #m:  235.0  #Car Weight [kg]
    m:   215.0  #Car Weight [kg]
    g:   9.81   #Gravity force
    Iz:  300  #Inertial force I_zz
    #Iz: 400  #Inertial force I_zz
    #Iz: 859


  kinematics:
    track: 1.2
    a: 0.880
    b: 0.660 
    # h: 0.1 #heigh of CG (use to tune load transfer)
    h: 0.0 # 0.330 é o valor original

  engine:
    #gr: 15.21   #gear ratio
    gr: 12.65   #gear ratio

  #Continental C19 tyres
  tire:
    # sigma: [1961.499057, 387.402715756,
    #         0.      ,       0.,
    #         0.      ,       0.]

    sigma_00: 1961.499057
    sigma_00: 4000
    # sigma_01: 387.402715756
    # sigma_01: 887.402715756
    # sigma_01: 400
    sigma_10: 1.0
    sigma_11: 1.0
    sigma_20: 0.0
    sigma_21: 0.0

    J_f: 4    #front
    J_r: 4    #rear

    # mu_k: [1.101217158875779, 0
    #       0,      1.101217158875779]s

    mu_k_00: 1.101217158875779
    mu_k_01: 0.
    mu_k_10: 0.
    mu_k_11: 1.101217158875779
    mu_k_00: 0.5
    # mu_k_01: 0.
    # mu_k_10: 0.
    mu_k_11: 0.5

    # mu_s: [2.6564, 0
    #       0,      2.6564]
    
    mu_s_00: 2.49595578
    mu_s_01: 0.0
    mu_s_10: 0.0
    mu_s_11: 2.49595578

    # mu_s_00: 3.49595578

    # mu_s_00: 4.49595578
    # mu_s_01: 0.0  
    # mu_s_10: 0.0
    # mu_s_11: 4.49595578ZZ

    gamma: 1
    vs: 2.363585263291744
    # vs: 0.8
    kx: 1.4 #probably not used
    ky: 1.4 #probably not used
    # kz: 86000
    kz: 30000
    #r: 0.252
    r: 0.2285
    #r: 0.2385

  gps:

    coord_x: 0 #coordinates of gps(ahrs) in the car
    coord_y: 0
